version: '3.8'

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: naturalcycle
    volumes:
      - ./postgres:/var/lib/postgresql/data

  db_backup:
    image: postgres:15.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: db_backup
    depends_on:
      - db
    volumes:
      - ./backups:/backups
    entrypoint:
      [
        'sh',
        '-c',
        'echo "*:*:*:$POSTGRES_USER:$POSTGRES_PASSWORD" > ~/.pgpass && chmod 600 ~/.pgpass && while true; do pg_dump -U "$POSTGRES_USER" -h db "$POSTGRES_DB" > /backups/backup_$(date +"%Y%m%d%H%M").sql; sleep 604800; done',
      ]
